# -*- coding: utf-8 -*-
"""Lables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAQDw3l_EhS-hW4oZS-OnGEn7lbG9Upt

Garment Label Detection Using YOLO11

This notebook implements a computer vision-based garment label detection system using the YOLO11 object detection framework.

The system is designed to identify and localize three types of garment labels:

- NoLabel
- ProductLabel
- Size Label

1. Install Required Libraries

The required Python libraries are installed before starting the model development process.

The main libraries used in this notebook are:

- Ultralytics for YOLO11 model training, validation, and prediction.
- Pytesseract for optical character recognition (OCR)-related processing.
"""

pip install ultralytics

pip install pytesseract

"""2. Import Required Libraries

The necessary Python libraries and modules are imported for dataset handling, YAML configuration, file management, and YOLO11 model development.

The Google Colab files module is also used to upload the dataset directly into the Colab environment.
"""

from google.colab import files
import zipfile
import os
import shutil
import yaml
from ultralytics import YOLO

print("All libraries imported successfully!")

"""3. Upload the Dataset

The annotated garment-label dataset is uploaded as a ZIP file into the Google Colab environment.

The uploaded dataset contains the images and corresponding YOLO-format annotation files required for object detection training.
"""

# This will open a file upload dialog
print(" Click 'Choose Files' and select your dataset ZIP file")
print("  (The file should be named like: 'My First Project.v5i.yolov11 (1).zip')")

uploaded = files.upload()

# Check what was uploaded
print(f"\n Uploaded: {list(uploaded.keys())}")

"""4. Extract the Dataset

The uploaded ZIP file is extracted into the /content/ directory.

After extraction, the contents of the directory are checked to identify the dataset folders and confirm that the required files are available for further processing.
"""

# Extract the ZIP file
for filename in uploaded.keys():
    if filename.endswith('.zip'):
        print(f"Extracting {filename}...")
        with zipfile.ZipFile(filename, 'r') as zip_ref:
            zip_ref.extractall('/content/')
        os.remove(filename)  # Remove ZIP to save space
        print(" Extraction complete!")

# Show what was extracted
print("\n Extracted contents:")
for item in os.listdir('/content/'):
    if os.path.isdir(os.path.join('/content/', item)):
        # Check if it's our dataset folder
        if 'project' in item.lower() or 'yolo' in item.lower() or 'v5i' in item.lower():
            print(f"   {item}/")
            # Show what's inside
            try:
                for sub in os.listdir(os.path.join('/content/', item))[:5]:
                    print(f"      {sub}")
            except:
                pass

"""5. Configure the YOLO Dataset

A data.yaml configuration file is created to define the dataset structure and class information required by YOLO11.

The configuration specifies:

- Dataset root path
- Training image directory
- Validation image directory
- Test image directory
- Number of object classes
- Class names

The three object classes used in this dataset are NoLabel, ProductLabel, and size label.
"""

import yaml
import os

print(" Creating data.yaml...")

# Create data.yaml content
data = {
    'path': '/content',
    'train': 'train/images',
    'val': 'valid/images',  # You have valid folder now!
    'test': 'test/images',
    'nc': 3,  # Number of classes (adjust if different)
    'names': ['NoLabel', 'ProductLabel', 'size label']  # Update with your class names
}

# Save to /content/data.yaml
with open('/content/data.yaml', 'w') as f:
    yaml.dump(data, f, default_flow_style=False)

print(" data.yaml created at /content/data.yaml")
print("\n Content:")
print(f"   path: {data['path']}")
print(f"   train: {data['train']}")
print(f"   val: {data['val']}")
print(f"   test: {data['test']}")
print(f"   nc: {data['nc']}")
print(f"   names: {data['names']}")

"""6. Verify Dataset Structure

The dataset structure is verified before model training.

The verification process checks whether the following directories and annotation files are available:

- Training images
- Training labels
- Validation images
- Test images
- data.yaml

This step helps identify missing directories or dataset-structure problems before starting the training process.
"""

import os

print("\n VERIFYING DATASET STRUCTURE")
print("="*50)

# Check train folder
if os.path.exists('/content/train/images'):
    train_images = len(os.listdir('/content/train/images'))
    print(f"✅ Training images: {train_images}")
else:
    print("❌ /content/train/images not found!")

# Check train labels
if os.path.exists('/content/train/labels'):
    train_labels = len(os.listdir('/content/train/labels'))
    print(f"✅ Training labels: {train_labels}")
else:
    print("❌ /content/train/labels not found!")

# Check valid folder
if os.path.exists('/content/valid/images'):
    valid_images = len(os.listdir('/content/valid/images'))
    print(f"✅ Validation images: {valid_images}")
else:
    print("❌ /content/valid/images not found!")

# Check test folder
if os.path.exists('/content/test/images'):
    test_images = len(os.listdir('/content/test/images'))
    print(f"✅ Test images: {test_images}")
else:
    print("❌ /content/test/images not found!")

print("="*50)

# Show data.yaml content
print("\n📄 data.yaml:")
with open('/content/data.yaml', 'r') as f:
    print(f.read())

"""7. Check GPU Availability

GPU availability is checked to ensure that model training can be accelerated using CUDA.

The notebook verifies:

- Whether CUDA is available
- The number of available GPU devices
- The name of the detected GPU

A Tesla T4 GPU is detected in the current Colab environment.
"""

import torch
print("CUDA available:", torch.cuda.is_available())
print("Device count:", torch.cuda.device_count())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

"""8. Define Dataset Paths

The paths for the original and augmented datasets are defined.

The notebook also verifies whether the required dataset directories and data.yaml file exist and counts the available training images.

The augmented training dataset currently contains 1,834 images.
"""

# Re-define paths (since Colab restarted)
original_path = "/content/original_dataset"
augmented_path = "/content/augmented_dataset"

# Verify they exist
import os
print(f"Original dataset: {os.path.exists(original_path)}")
print(f"Augmented dataset: {os.path.exists(augmented_path)}")
print(f"data.yaml: {os.path.exists(f'{augmented_path}/data.yaml')}")

# Count images to confirm
img_dir = f"{augmented_path}/train/images"
if os.path.exists(img_dir):
    print(f"Total training images: {len(os.listdir(img_dir))}")

""" 9. Train the General YOLO11 Model

The general garment-label detection model is trained using the YOLO11n pretrained model.

The training configuration includes:

- Model: YOLO11n
- Epochs: 100
- Image size: 416 × 416
- Batch size: 4
- Data augmentation: Enabled
- Early stopping patience: 20 epochs
- Device: GPU
- Workers: 0

The pretrained YOLO11n weights are fine-tuned on the prepared garment-label dataset to detect the three defined classes.
"""

# ============================================
# TRAIN YOLO11 — SELF-CONTAINED CELL
# ============================================

import os
import gc
import torch
from ultralytics import YOLO

# ---- Step 1: Define paths (in case runtime restarted) ----
augmented_path = "/content/augmented_dataset"
data_yaml = f"{augmented_path}/data.yaml"

# ---- Step 2: Verify ----
if not os.path.exists(data_yaml):
    raise FileNotFoundError(f"❌ data.yaml not found at {data_yaml}")
print(f"✅ Found data.yaml")
print(f"✅ Training images: {len(os.listdir(f'{augmented_path}/train/images'))}")

# ---- Step 3: Free memory ----
gc.collect()
torch.cuda.empty_cache()

# ---- Step 4: Train with light settings ----
model = YOLO('yolo11n.pt')

results = model.train(
    data=data_yaml,
    epochs=100,
    patience=20,      # ⏹ Early stopping
    imgsz=416,        # ⬇ Safe for Colab
    batch=4,          # ⬇ Safe for Colab
    augment=True,
    device=0,         # 🚀 GPU
    cache=False,
    workers=0,        # ⬇ No multiprocessing
    name='garment_aug_run_safe'
)

print("\n✅ Training complete!")
print("   Best model: runs/detect/garment_aug_run_safe/weights/best.pt")

"""10. Inspect the Colab Environment and Trained Models

The contents of the /content/ directory are inspected to verify that the required datasets, training outputs, and model weights have been generated successfully.

The notebook searches for trained best.pt model files so that the best-performing model can be identified and used for subsequent evaluation and testing.
"""

import os

print(" Checking /content:")
print("="*60)

for item in sorted(os.listdir('/content')):
    full_path = os.path.join('/content', item)
    if os.path.isdir(full_path):
        try:
            count = len(os.listdir(full_path))
            print(f"   {item}/  ({count} items)")
        except:
            print(f"   {item}/")
    else:
        print(f"   {item}")

print("\n🔍 Looking for trained models:")
print("="*60)

found_model = False
for root, dirs, files in os.walk('/content'):
    for f in files:
        if f == 'best.pt':
            print(f"   Found: {os.path.join(root, f)}")
            found_model = True

if not found_model:
    print("   No trained model found anywhere")

"""11. Compare Trained Models

The available trained YOLO11 models are loaded and evaluated for comparison.

The purpose of this step is to identify the model that provides the most suitable detection performance for the garment-label detection task.

"""

from ultralytics import YOLO
import os, yaml

# Define data.yaml path
augmented_path = "/content/augmented_dataset"
data_yaml = f"{augmented_path}/data.yaml"

# Verify data.yaml exists
if not os.path.exists(data_yaml):
    # Fallback - create a new one
    data = {"nc": 3, "names": ["NoLabel", "ProductLabel", "size label"]}
    data['path'] = augmented_path
    data['train'] = 'train/images'
    data['val'] = 'train/images'
    with open(data_yaml, "w") as f:
        yaml.dump(data, f)
    print(" Created new data.yaml")

# ---------- Model 1: garment_aug_run ----------
print("="*60)
print(" MODEL 1: garment_aug_run")
print("="*60)

model1 = YOLO('/content/runs/detect/garment_aug_run/weights/best.pt')
metrics1 = model1.val(data=data_yaml, verbose=False)

print(f"  mAP50-95:  {metrics1.box.map:.4f}")
print(f"  mAP50:     {metrics1.box.map50:.4f}")
print(f"  Precision: {metrics1.box.mp:.4f}")
print(f"  Recall:    {metrics1.box.mr:.4f}")

# ---------- Model 2: garment_aug_run_safe ----------
print("\n" + "="*60)
print(" MODEL 2: garment_aug_run_safe")
print("="*60)

model2 = YOLO('/content/runs/detect/garment_aug_run_safe/weights/best.pt')
metrics2 = model2.val(data=data_yaml, verbose=False)

print(f"  mAP50-95:  {metrics2.box.map:.4f}")
print(f"  mAP50:     {metrics2.box.map50:.4f}")
print(f"  Precision: {metrics2.box.mp:.4f}")
print(f"  Recall:    {metrics2.box.mr:.4f}")

# ---------- Comparison ----------
print("\n" + "="*60)
print(" COMPARISON")
print("="*60)
print(f"{'Metric':<15} {'Run 1':<12} {'Run 2':<12} {'Baseline':<12}")
print("-"*50)
print(f"{'mAP50-95':<15} {metrics1.box.map:<12.4f} {metrics2.box.map:<12.4f} 0.3370")
print(f"{'mAP50':<15} {metrics1.box.map50:<12.4f} {metrics2.box.map50:<12.4f} 0.7520")
print(f"{'Precision':<15} {metrics1.box.mp:<12.4f} {metrics2.box.mp:<12.4f} 0.7410")
print(f"{'Recall':<15} {metrics1.box.mr:<12.4f} {metrics2.box.mr:<12.4f} 0.6550")

# ---------- Per-class for best ----------
print("\n" + "="*60)
print(" PER-CLASS (whichever did better)")
print("="*60)

if metrics2.box.map > metrics1.box.map:
    best_metrics = metrics2
    best_name = "garment_aug_run_safe"
else:
    best_metrics = metrics1
    best_name = "garment_aug_run"

print(f"Best model: {best_name}\n")
for i, name in enumerate(best_metrics.names):
    ap = best_metrics.box.ap[i]
    status = "✅" if ap >= 0.5 else "⚠️" if ap >= 0.3 else "❌"
    print(f"  {status} {name:<15}: mAP50-95 = {ap:.4f} ({ap*100:.1f}%)")

"""12. Save and Download the Best Model

The selected best-performing model is prepared for storage and download.

The trained model weights are saved so that the model can be reused later for testing and integration into the garment inspection system without requiring the model to be trained again.
"""

from ultralytics import YOLO
import os, yaml, shutil
from google.colab import drive, files

# ============================================================
# STEP 1: Prepare data.yaml
# ============================================================
augmented_path = "/content/augmented_dataset"
data_yaml = f"{augmented_path}/data.yaml"

data = {
    'path':  augmented_path,
    'train': 'train/images',
    'val':   'train/images',
    'test':  'train/images',
    'nc':    3,
    'names': ['NoLabel', 'ProductLabel', 'size label']
}
with open(data_yaml, 'w') as f:
    yaml.dump(data, f)
print(f"✅ data.yaml ready: {data_yaml}")

# ============================================================
# STEP 2: Evaluate Model 1
# ============================================================
print("\n" + "="*60)
print(" MODEL 1: garment_aug_run")
print("="*60)

model1 = YOLO('/content/runs/detect/garment_aug_run/weights/best.pt')
m1 = model1.val(data=data_yaml, verbose=False)

print(f"  mAP50-95:  {m1.box.map:.4f}")
print(f"  mAP50:     {m1.box.map50:.4f}")
print(f"  Precision: {m1.box.mp:.4f}")
print(f"  Recall:    {m1.box.mr:.4f}")

# ============================================================
# STEP 3: Evaluate Model 2
# ============================================================
print("\n" + "="*60)
print(" MODEL 2: garment_aug_run_safe")
print("="*60)

model2 = YOLO('/content/runs/detect/garment_aug_run_safe/weights/best.pt')
m2 = model2.val(data=data_yaml, verbose=False)

print(f"  mAP50-95:  {m2.box.map:.4f}")
print(f"  mAP50:     {m2.box.map50:.4f}")
print(f"  Precision: {m2.box.mp:.4f}")
print(f"  Recall:    {m2.box.mr:.4f}")

# ============================================================
# STEP 4: Compare with Baseline
# ============================================================
print("\n" + "="*60)
print(" COMPARISON vs BASELINE")
print("="*60)
print(f"{'Metric':<12} {'Baseline':<12} {'Model 1':<12} {'Model 2':<12}")
print("-"*55)
print(f"{'mAP50-95':<12} {0.3370:<12.4f} {m1.box.map:<12.4f} {m2.box.map:<12.4f}")
print(f"{'mAP50':<12} {0.7520:<12.4f} {m1.box.map50:<12.4f} {m2.box.map50:<12.4f}")
print(f"{'Precision':<12} {0.7410:<12.4f} {m1.box.mp:<12.4f} {m2.box.mp:<12.4f}")
print(f"{'Recall':<12} {0.6550:<12.4f} {m1.box.mr:<12.4f} {m2.box.mr:<12.4f}")

# ============================================================
# STEP 5: Pick the best model
# ============================================================
if m2.box.map >= m1.box.map:
    best_metrics = m2
    best_name = "garment_aug_run_safe"
    best_path = "/content/runs/detect/garment_aug_run_safe/weights/best.pt"
else:
    best_metrics = m1
    best_name = "garment_aug_run"
    best_path = "/content/runs/detect/garment_aug_run/weights/best.pt"

print("\n" + "="*60)
print(f" BEST MODEL: {best_name}")
print("="*60)
print(f"  mAP50-95:  {best_metrics.box.map:.4f} ({best_metrics.box.map*100:.2f}%)")
print(f"  mAP50:     {best_metrics.box.map50:.4f} ({best_metrics.box.map50*100:.2f}%)")
print(f"  Precision: {best_metrics.box.mp:.4f} ({best_metrics.box.mp*100:.2f}%)")
print(f"  Recall:    {best_metrics.box.mr:.4f} ({best_metrics.box.mr*100:.2f}%)")

# ============================================================
# STEP 6: Per-class accuracy
# ============================================================
print(f"\n PER-CLASS ACCURACY:")
for i, name in enumerate(best_metrics.names):
    ap = best_metrics.box.ap[i]
    status = "✅" if ap >= 0.5 else "⚠️" if ap >= 0.3 else "❌"
    print(f"  {status} {name:<15}: mAP50-95 = {ap:.4f} ({ap*100:.1f}%)")

# ============================================================
# STEP 7: Save best model to Google Drive
# ============================================================
drive.mount('/content/drive')

drive_model_path = '/content/drive/MyDrive/best_model_augmented.pt'
shutil.copy(best_path, drive_model_path)

# Save metrics text file
metrics_txt = '/content/drive/MyDrive/model_metrics.txt'
with open(metrics_txt, 'w') as f:
    f.write("YOLO11n — Missing Labels Detection (Augmented Dataset)\n")
    f.write("="*60 + "\n\n")
    f.write(f"Best model: {best_path}\n\n")
    f.write(f"mAP50-95:  {best_metrics.box.map:.4f}\n")
    f.write(f"mAP50:     {best_metrics.box.map50:.4f}\n")
    f.write(f"Precision: {best_metrics.box.mp:.4f}\n")
    f.write(f"Recall:    {best_metrics.box.mr:.4f}\n\n")
    f.write("Per-class mAP50-95:\n")
    for i, name in enumerate(best_metrics.names):
        f.write(f"  {name}: {best_metrics.box.ap[i]:.4f}\n")

print(f"\n Saved to Drive:")
print(f"   Model:   {drive_model_path}")
print(f"   Metrics: {metrics_txt}")

# ============================================================
# STEP 8: Download to your computer
# ============================================================
print("\n Downloading to your computer...")
files.download(drive_model_path)
files.download(metrics_txt)
print(" Downloads started!")

"""Evaluate the Best General Model

The selected best-performing general detection model is validated using the prepared dataset.
"""

from ultralytics import YOLO

# Load your best model
model = YOLO('/content/runs/detect/garment_aug_run_safe/weights/best.pt')

# Run validation
metrics = model.val(data='/content/augmented_dataset/data.yaml')

# Overall metrics
print("="*60)
print(" MODEL ACCURACY")
print("="*60)
print(f"mAP50-95:  {metrics.box.map:.4f}  ({metrics.box.map*100:.2f}%)")
print(f"mAP50:     {metrics.box.map50:.4f}  ({metrics.box.map50*100:.2f}%)")
print(f"Precision: {metrics.box.mp:.4f}  ({metrics.box.mp*100:.2f}%)")
print(f"Recall:    {metrics.box.mr:.4f}  ({metrics.box.mr*100:.2f}%)")

# Per-class accuracy
print("\n PER-CLASS ACCURACY:")
for i, name in enumerate(metrics.names):
    ap = metrics.box.ap[i]
    status = "✅" if ap >= 0.5 else "⚠️" if ap >= 0.3 else "❌"
    print(f"  {status} {name:<15}: mAP50-95 = {ap:.4f} ({ap*100:.1f}%)")

"""14. Create a Dedicated Size-Label Dataset

The size-label class is analyzed separately because detecting small size labels can be more challenging than detecting larger label regions.

Images containing the size-label class are extracted from the augmented dataset to create a dedicated dataset for specialist model training.

This allows a separate object detection model to focus specifically on size-label detection.
"""

import os, shutil, yaml

# Source: augmented dataset
src_img_dir = "/content/augmented_dataset/train/images"
src_lbl_dir = "/content/augmented_dataset/train/labels"

# New dataset for size_label only
dst_root    = "/content/size_label_dataset"
dst_img_dir = f"{dst_root}/train/images"
dst_lbl_dir = f"{dst_root}/train/labels"

os.makedirs(dst_img_dir, exist_ok=True)
os.makedirs(dst_lbl_dir, exist_ok=True)

SIZE_LABEL_CLASS_ID = 2   # size label = class 2 in your dataset

kept = 0
for lbl_file in os.listdir(src_lbl_dir):
    if not lbl_file.endswith(".txt"):
        continue
    lbl_path = os.path.join(src_lbl_dir, lbl_file)
    with open(lbl_path) as f:
        lines = f.readlines()

    # Keep only lines where class == 2 (size label)
    size_lines = [ln for ln in lines if ln.strip().split()[0] == str(SIZE_LABEL_CLASS_ID)]

    if not size_lines:
        continue   # skip images with no size-label instances

    # Save filtered label with class ID reset to 0 (single class)
    new_lines = []
    for ln in size_lines:
        parts = ln.strip().split()
        parts[0] = "0"          # re-index class 2 → 0
        new_lines.append(" ".join(parts) + "\n")

    with open(os.path.join(dst_lbl_dir, lbl_file), "w") as f:
        f.writelines(new_lines)

    # Copy the corresponding image
    base = os.path.splitext(lbl_file)[0]
    for ext in [".jpg", ".png", ".jpeg"]:
        src_img = os.path.join(src_img_dir, base + ext)
        if os.path.exists(src_img):
            shutil.copy(src_img, os.path.join(dst_img_dir, base + ext))
            break

    kept += 1

print(f"✅ Kept {kept} images containing size label")

"""15. Create the Size-Label Dataset Configuration

A separate data.yaml file is created for the dedicated size-label dataset.

Unlike the general model, this dataset contains only one object class:

- size label

The configuration is therefore defined with nc = 1.
"""

data = {
    "path":  dst_root,
    "train": "train/images",
    "val":   "train/images",
    "nc":    1,
    "names": ["size label"]
}

with open(f"{dst_root}/data.yaml", "w") as f:
    yaml.dump(data, f)

print(f"✅ data.yaml created at {dst_root}/data.yaml")

"""16. Train the Size-Label Specialist Model

A dedicated YOLO11s model is trained to detect size labels.

A larger input image size of 640 × 640 is used because size labels are relatively small objects and higher image resolution can provide more detailed visual information.

The training configuration includes:

- Model: YOLO11s
- Epochs: 25
- Image size: 640 × 640
- Batch size: 4
- Data augmentation: Enabled
- Early stopping: Enabled
- Device: GPU
"""

from ultralytics import YOLO

model = YOLO('yolo11s.pt')   # or 'yolo11n.pt' for faster

model.train(
    data=f"{dst_root}/data.yaml",
    epochs=25,
    patience=30,
    imgsz=640,           # ⬆ Bigger for small objects
    batch=4,
    augment=True,
    device=0,
    cache=False,
    workers=0,
    name='size_label_only'
)

print("✅ Dedicated size label model trained")

"""17. Evaluate the Size-Label Specialist Model

The trained size-label specialist model is validated using its dedicated dataset.

The evaluation measures the model's detection performance using:

- mAP@50–95
- mAP@50
- Precision
- Recall

These results are used to determine whether the specialist model improves size-label detection compared with the general detection model.
"""

from ultralytics import YOLO
import glob, os

# Find the LATEST size_label_only* run
candidates = sorted(
    glob.glob('/content/runs/detect/size_label_only*/weights/best.pt'),
    key=os.path.getmtime
)

if not candidates:
    print("❌ No trained size_label model found.")
else:
    model_path = candidates[-1]   # latest
    print(f"✅ Using: {model_path}")

    model = YOLO(model_path)
    metrics = model.val(data=f"{dst_root}/data.yaml", verbose=False)

    print("="*60)
    print("📊 SIZE LABEL SPECIALIST — ACCURACY")
    print("="*60)
    print(f"mAP50-95:  {metrics.box.map:.4f}  ({metrics.box.map*100:.2f}%)")
    print(f"mAP50:     {metrics.box.map50:.4f}  ({metrics.box.map50*100:.2f}%)")
    print(f"Precision: {metrics.box.mp:.4f}  ({metrics.box.mp*100:.2f}%)")
    print(f"Recall:    {metrics.box.mr:.4f}  ({metrics.box.mr*100:.2f}%)")

"""18. Analyze the Size-Label Annotations

The size-label annotations are analyzed to determine the number of images and object instances containing the size-label class.

This analysis helps verify the availability and distribution of size-label annotations before creating the final specialist dataset.
"""

import os
from collections import Counter

lbl_dir = "/content/augmented_dataset/train/labels"

total_files = 0
files_with_class2 = 0
class2_instances = 0
class_counter = Counter()

for f in os.listdir(lbl_dir):
    if not f.endswith(".txt"):
        continue
    total_files += 1
    has_class2 = False
    with open(os.path.join(lbl_dir, f)) as fh:
        for line in fh:
            if line.strip():
                cls = line.strip().split()[0]
                class_counter[cls] += 1
                if cls == "2":
                    has_class2 = True
                    class2_instances += 1
    if has_class2:
        files_with_class2 += 1

print(f"Total label files: {total_files}")
print(f"Files containing class '2': {files_with_class2}")
print(f"Total class '2' instances: {class2_instances}")
print(f"\nClass distribution:")
for cls, cnt in sorted(class_counter.items()):
    print(f"  Class {cls}: {cnt} instances")

"""19. Filter and Prepare the Size-Label Dataset

The dataset is filtered to retain images containing the size-label class.

The annotation files are also checked for different numerical representations of the class identifier, such as 2 and 2.0.

Only the required size-label annotations are retained for specialist model training.
"""

import os, shutil, yaml

# ==========================================
# STEP 1: Filter dataset — accept BOTH "2" and "2.0"
# ==========================================
src_img_dir = "/content/augmented_dataset/train/images"
src_lbl_dir = "/content/augmented_dataset/train/labels"

dst_root    = "/content/size_label_dataset_v3"
dst_img_dir = f"{dst_root}/train/images"
dst_lbl_dir = f"{dst_root}/train/labels"

# Clean old version if exists
if os.path.exists(dst_root):
    shutil.rmtree(dst_root)
os.makedirs(dst_img_dir, exist_ok=True)
os.makedirs(dst_lbl_dir, exist_ok=True)

SIZE_LABEL_ID = 2   # confirmed from per-class accuracy

kept = 0
size_instances = 0

for lbl_file in os.listdir(src_lbl_dir):
    if not lbl_file.endswith(".txt"):
        continue
    with open(os.path.join(src_lbl_dir, lbl_file)) as f:
        lines = f.readlines()

    # Accept "2" or "2.0"
    size_lines = []
    for ln in lines:
        parts = ln.strip().split()
        if not parts:
            continue
        try:
            cls_id = int(float(parts[0]))   # convert "2.0" → 2
        except ValueError:
            continue
        if cls_id == SIZE_LABEL_ID:
            # Re-index to 0 for single-class training
            parts[0] = "0"
            size_lines.append(" ".join(parts) + "\n")

    if not size_lines:
        continue

    # Save cleaned label
    with open(os.path.join(dst_lbl_dir, lbl_file), "w") as f:
        f.writelines(size_lines)

    # Copy image
    base = os.path.splitext(lbl_file)[0]
    for ext in [".jpg", ".png", ".jpeg"]:
        src = os.path.join(src_img_dir, base + ext)
        if os.path.exists(src):
            shutil.copy(src, os.path.join(dst_img_dir, base + ext))
            break

    kept += 1
    size_instances += len(size_lines)

print(f"✅ Filtered correctly:")
print(f"   Images kept: {kept}")
print(f"   size label instances: {size_instances}")

# ==========================================
# STEP 2: Create data.yaml
# ==========================================
with open(f"{dst_root}/data.yaml", "w") as f:
    yaml.dump({
        "path":  dst_root,
        "train": "train/images",
        "val":   "train/images",
        "nc":    1,
        "names": ["size label"]
    }, f)

print(f"✅ data.yaml created")

"""20. Clean and Augment the Dataset

The annotation files are cleaned to ensure that class identifiers are stored consistently as integer values.

The prepared dataset is then used with YOLO11's built-in augmentation techniques during training.

Data augmentation helps expose the model to variations in the training images and can improve its ability to generalize to unseen garment images.
"""

# Clean ALL label files — convert floats to ints
aug_lbl_dir = "/content/augmented_dataset/train/labels"
fixed = 0

for f in os.listdir(aug_lbl_dir):
    if not f.endswith(".txt"):
        continue
    path = os.path.join(aug_lbl_dir, f)
    with open(path) as fh:
        lines = fh.readlines()

    new_lines = []
    changed = False
    for ln in lines:
        parts = ln.strip().split()
        if not parts:
            continue
        try:
            cls_id = int(float(parts[0]))
            if parts[0] != str(cls_id):
                changed = True
            new_lines.append(f"{cls_id} {' '.join(parts[1:])}\n")
        except:
            new_lines.append(ln)

    if changed:
        with open(path, "w") as fh:
            fh.writelines(new_lines)
        fixed += 1

print(f"✅ Fixed {fixed} label files (converted float class IDs → int)")

"""21. Train the Final Size-Label Specialist Model

The final specialist model is trained using the cleaned size-label dataset.

The model is trained using YOLO11s with a 640 × 640 input size and GPU acceleration.

The resulting best model weights are saved for integration with the general garment-label detection model.
"""

from ultralytics import YOLO
import glob, os, shutil
from google.colab import drive

# ==========================================
# Train specialist size label model
# ==========================================
print("🚀 Training size label specialist model...")
print("   Dataset: 278 images, 1 class")
print("   Estimated time: ~25-30 minutes")

model = YOLO('yolo11s.pt')

model.train(
    data="/content/size_label_dataset_v3/data.yaml",
    epochs=25,          # ⬆ More epochs for better accuracy
    patience=20,         # Early stopping
    imgsz=640,
    batch=4,
    augment=True,
    device=0,
    cache=False,
    workers=0,
    name='size_label_final'
)

print("\n✅ Training done")

# ==========================================
# Evaluate
# ==========================================
candidates = sorted(
    glob.glob('/content/runs/detect/size_label_final*/weights/best.pt'),
    key=os.path.getmtime
)
model_path = candidates[-1]

model = YOLO(model_path)
metrics = model.val(data="/content/size_label_dataset_v3/data.yaml", verbose=False)

print("="*60)
print("📊 SIZE LABEL SPECIALIST — ACCURACY")
print("="*60)
print(f"mAP50-95:  {metrics.box.map:.4f}  ({metrics.box.map*100:.2f}%)")
print(f"mAP50:     {metrics.box.map50:.4f}  ({metrics.box.map50*100:.2f}%)")
print(f"Precision: {metrics.box.mp:.4f}  ({metrics.box.mp*100:.2f}%)")
print(f"Recall:    {metrics.box.mr:.4f}  ({metrics.box.mr*100:.2f}%)")

# ==========================================
# Save to Drive
# ==========================================
drive.mount('/content/drive')
shutil.copy(
    model_path,
    '/content/drive/MyDrive/size_label_specialist_final.pt'
)
print("\n✅ Saved to Drive: /content/drive/MyDrive/size_label_specialist_final.pt")

"""22. Test the Combined Detection System

The final testing stage loads two models:

1. The general garment-label detection model
2. The dedicated size-label specialist model

Both models are applied to the input garment image.

The combined detection process allows the system to detect the general garment-label classes while using the specialist model to improve size-label detection.
"""

from ultralytics import YOLO
import os, glob, cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

# ==========================================
# Load both models
# ==========================================
general = YOLO('/content/drive/MyDrive/best_model_augmented.pt')
specialist = YOLO('/content/drive/MyDrive/size_label_specialist_final.pt')

# ==========================================
# Combined detection function
# ==========================================
def detect_garment_defects(image_path, conf=0.25):
    r1 = general.predict(image_path, conf=conf, verbose=False)[0]
    r2 = specialist.predict(image_path, conf=conf, verbose=False)[0]

    results = {
        'NoLabel':       [],
        'ProductLabel':  [],
        'size label':    []
    }

    # From general model: keep NoLabel (0) and ProductLabel (1)
    for box in r1.boxes:
        cls = int(box.cls[0])
        if cls == 0:
            results['NoLabel'].append(box)
        elif cls == 1:
            results['ProductLabel'].append(box)

    # From specialist: all detections are size label
    for box in r2.boxes:
        results['size label'].append(box)

    return results, r1, r2

# ==========================================
# Pick a real image from your dataset
# ==========================================
test_images = glob.glob('/content/test/images/*.jpg') or \
              glob.glob('/content/augmented_dataset/train/images/*.jpg')

if not test_images:
    print(" No images found. Check if dataset exists.")
else:
    img_path = test_images[0]
    print(f" Testing on: {img_path}\n")

    # Run combined detection
    results, r1, r2 = detect_garment_defects(img_path)

    print("="*60)
    print(" DETECTIONS")
    print("="*60)
    print(f"  NoLabel:      {len(results['NoLabel'])}")
    print(f"  ProductLabel: {len(results['ProductLabel'])}")
    print(f"  size label:   {len(results['size label'])}")

    # ==========================================
    # Visualize
    # ==========================================
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Draw detections on image
    for label, boxes, color in [
        ('NoLabel',      results['NoLabel'],      (255, 0, 0)),
        ('ProductLabel', results['ProductLabel'], (0, 255, 0)),
        ('size label',   results['size label'],   (0, 0, 255)),
    ]:
        for box in boxes:
            xyxy = box.xyxy[0].cpu().numpy().astype(int)
            x1, y1, x2, y2 = xyxy
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, label, (x1, y1 - 5),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    print("\n📸 Visualization:")
    plt.figure(figsize=(12, 8))
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Combined Detection — {os.path.basename(img_path)}")
    plt.show()

"""23. Visualize and Evaluate the Detection Results

The final evaluation stage visualizes the performance of the trained models.

The notebook generates evaluation outputs such as:

- Validation loss curves
- Confusion matrix
- Sample detection results
- Per-class performance
- Combined model performance

These visualizations provide a clearer understanding of the strengths and limitations of the developed garment-label detection system.
"""

# ============================================
# VALIDATION LOSS + CONFUSION MATRIX + SAMPLE PREDICTIONS
# ============================================

!pip install ultralytics seaborn -q

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import os, glob, cv2
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
from google.colab import drive

# Style
plt.rcParams['figure.dpi'] = 100
plt.rcParams['font.size'] = 11
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3

os.makedirs('/content/graphs', exist_ok=True)

# Mount Drive (in case session reset)
if not os.path.exists('/content/drive/MyDrive'):
    drive.mount('/content/drive')

# ==========================================
# GRAPH 6: VALIDATION LOSS CURVES
# ==========================================
print(" Graph 6: Validation Loss Curves...")

# Find the latest training run's results.csv
results_files = sorted(glob.glob('/content/runs/detect/*/results.csv'),
                       key=os.path.getmtime)

if results_files:
    df = pd.read_csv(results_files[-1])
    print(f"   Using: {results_files[-1]}")
    print(f"   Columns: {list(df.columns)[:8]}")

    fig, axes = plt.subplots(1, 2, figsize=(15, 6))
    fig.suptitle(' Validation Loss Curves', fontsize=16, fontweight='bold')

    # Find val loss columns (might be named differently)
    box_val_col = None
    cls_val_col = None
    dfl_val_col = None

    for col in df.columns:
        if 'val' in col.lower() and 'box' in col.lower():
            box_val_col = col
        elif 'val' in col.lower() and 'cls' in col.lower():
            cls_val_col = col
        elif 'val' in col.lower() and 'dfl' in col.lower():
            dfl_val_col = col

    # Left plot: Validation losses
    ax = axes[0]
    has_data = False
    if box_val_col:
        ax.plot(df['epoch'], df[box_val_col], label='Val Box Loss',
                linewidth=2, color='blue', marker='o', markersize=3)
        has_data = True
    if cls_val_col:
        ax.plot(df['epoch'], df[cls_val_col], label='Val Class Loss',
                linewidth=2, color='orange', marker='s', markersize=3)
        has_data = True
    if dfl_val_col:
        ax.plot(df['epoch'], df[dfl_val_col], label='Val DFL Loss',
                linewidth=2, color='green', marker='^', markersize=3)
        has_data = True

    if not has_data:
        # Fallback: use training losses
        for col in df.columns:
            if 'box_loss' in col:
                ax.plot(df['epoch'], df[col], label=col, linewidth=2)
            elif 'cls_loss' in col:
                ax.plot(df['epoch'], df[col], label=col, linewidth=2)

    ax.set_xlabel('Epoch', fontsize=12)
    ax.set_ylabel('Loss', fontsize=12)
    ax.set_title('Validation Losses Over Time', fontsize=13, fontweight='bold')
    ax.legend(fontsize=10)

    # Right plot: Train vs Val (for overfitting detection)
    ax = axes[1]
    if 'train/box_loss' in df.columns:
        ax.plot(df['epoch'], df['train/box_loss'], label='Train Box Loss',
                linewidth=2, color='blue', linestyle='-')
    if box_val_col:
        ax.plot(df['epoch'], df[box_val_col], label='Val Box Loss',
                linewidth=2, color='red', linestyle='--')

    ax.set_xlabel('Epoch', fontsize=12)
    ax.set_ylabel('Loss', fontsize=12)
    ax.set_title('Train vs Validation Loss (Overfitting Check)', fontsize=13, fontweight='bold')
    ax.legend(fontsize=10)

    plt.tight_layout()
    plt.savefig('/content/graphs/06_validation_loss.png', dpi=200, bbox_inches='tight')
    plt.show()
    print(" Saved: 06_validation_loss.png")
else:
    print("    No training results.csv found — skipping")


# ==========================================
# GRAPH 7: CONFUSION MATRIX (Custom Heatmap)
# ==========================================
print("\n Graph 7: Confusion Matrix...")

# Load the best model
model = YOLO('/content/drive/MyDrive/best_model_augmented.pt')

# Run validation
metrics = model.val(
    data='/content/augmented_dataset/data.yaml',
    verbose=False,
    plots=True  # generates confusion_matrix.png automatically
)

# Find the confusion matrix image generated by YOLO
cm_files = sorted(glob.glob('/content/runs/detect/val*/confusion_matrix.png'),
                  key=os.path.getmtime)

if cm_files:
    print(f"   Found YOLO-generated: {cm_files[-1]}")

    # Display it in a clean matplotlib format
    img = cv2.imread(cm_files[-1])
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(12, 10))
    plt.imshow(img)
    plt.axis('off')
    plt.title(' Confusion Matrix — Combined System', fontsize=15, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.savefig('/content/graphs/07_confusion_matrix.png', dpi=200, bbox_inches='tight')
    plt.show()
    print("Saved: 07_confusion_matrix.png")
else:
    print("    No confusion matrix found — generating custom one...")

    # Build a custom confusion matrix from metrics
    class_names = metrics.names
    n = len(class_names)

    # Get per-class metrics from YOLO
    # Approximate CM from precision/recall (not perfect but informative)
    cm = np.zeros((n, n))
    for i in range(n):
        p = metrics.box.p[i]
        r = metrics.box.r[i]
        # Rough diagonal estimate
        cm[i, i] = r * 100

    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='.1f', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names,
                cbar_kws={'label': 'Recall %'}, ax=ax)
    ax.set_xlabel('Predicted', fontsize=12, fontweight='bold')
    ax.set_ylabel('Actual', fontsize=12, fontweight='bold')
    ax.set_title(' Confusion Matrix (Approximation)', fontsize=15, fontweight='bold')

    plt.tight_layout()
    plt.savefig('/content/graphs/07_confusion_matrix.png', dpi=200, bbox_inches='tight')
    plt.show()
    print(" Saved: 07_confusion_matrix.png (approximation)")


# ==========================================
# GRAPH 8: SAMPLE PREDICTIONS
# ==========================================
print("\n Graph 8: Sample Predictions...")

# Load specialist model too
specialist = YOLO('/content/drive/MyDrive/size_label_specialist_final.pt')

# Get test images
test_dir = '/content/test/images'
if not os.path.exists(test_dir):
    test_dir = '/content/augmented_dataset/train/images'

test_images = sorted(glob.glob(f'{test_dir}/*.jpg'))[:6]

if test_images:
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    fig.suptitle(' Sample Predictions — Combined Detection System',
                 fontsize=18, fontweight='bold')
    axes = axes.flatten()

    class_colors = {
        'NoLabel':      (255, 0, 0),      # Blue in RGB
        'ProductLabel': (0, 255, 0),      # Green
        'size label':   (0, 0, 255),      # Red
    }

    for idx, img_path in enumerate(test_images):
        # Run general model
        r1 = model.predict(img_path, conf=0.25, verbose=False)[0]
        # Run specialist
        r2 = specialist.predict(img_path, conf=0.25, verbose=False)[0]

        # Load image
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Draw general model detections
        for box in r1.boxes:
            cls = int(box.cls[0])
            if cls not in (0, 1):
                continue
            label = 'NoLabel' if cls == 0 else 'ProductLabel'
            color = class_colors[label]
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, f'{label}', (x1, y1-5),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        # Draw specialist detections
        for box in r2.boxes:
            color = class_colors['size label']
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy().astype(int)
            cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
            cv2.putText(img, 'size label', (x1, y1-5),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        # Show
        axes[idx].imshow(img)
        axes[idx].axis('off')

        # Count detections
        n_no  = sum(1 for b in r1.boxes if int(b.cls[0]) == 0)
        n_pr  = sum(1 for b in r1.boxes if int(b.cls[0]) == 1)
        n_sz  = len(r2.boxes)

        verdict = 'FAIL' if (n_no > 0 or n_sz > 0) else 'PASS'
        axes[idx].set_title(
            f'{os.path.basename(img_path)[:30]}...\n'
            f'NoLabel={n_no} | ProductLabel={n_pr} | size label={n_sz}\n'
            f'Verdict: {verdict}',
            fontsize=9, fontweight='bold'
        )

    plt.tight_layout()
    plt.savefig('/content/graphs/08_sample_predictions.png', dpi=200, bbox_inches='tight')
    plt.show()
    print(" Saved: 08_sample_predictions.png")
else:
    print("    No test images found")


# ==========================================
# BONUS: Download all graphs
# ==========================================
print("\n" + "="*60)
print(" Packaging all graphs...")
print("="*60)

from google.colab import files
import shutil

shutil.make_archive('/content/garment_defect_graphs_v2', 'zip', '/content/graphs')
files.download('/content/garment_defect_graphs_v2.zip')

print("\n All graphs downloaded!")
print("\n New graphs created:")
print("  6. 06_validation_loss.png      — Val loss + overfitting check")
print("  7. 07_confusion_matrix.png     — Confusion matrix")
print("  8. 08_sample_predictions.png   — 6 predictions with bounding boxes")

"""24. Calculate Combined Model Performance

The best per-class mAP@50–95 values obtained from the trained models are combined to provide an overall reference value for the proposed detection system.

The calculation considers the best available performance for:

- NoLabel
- ProductLabel
- size label

This provides a summary of the detection performance achieved by combining the general and specialist models.
"""

# Best per-class values from your runs
best_per_class = {
    'NoLabel':      0.816,   # from general model
    'ProductLabel': 0.787,   # from general model
    'size label':   0.491,   # from specialist model (49.09%)
}

combined_avg = sum(best_per_class.values()) / len(best_per_class)
print(f"Combined system mAP50-95: {combined_avg:.4f} ({combined_avg*100:.2f}%)")