from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import os

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()
    
    def _add_custom_styles(self):
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a237e'),
            alignment=TA_CENTER,
            spaceAfter=30
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#0d47a1'),
            spaceAfter=12
        ))
    
    def generate_report(self, inspections, defects, period='weekly', user_name='Operator'):
        """
        Generate PDF report from inspections and defects data
        
        Args:
            inspections: List of InspectionSession objects
            defects: List of Defect objects
            period: 'weekly', 'monthly', or 'annual'
            user_name: Name of the user generating the report
        
        Returns:
            str: Path to the generated PDF file
        """
        # Create reports directory in the ROOT folder (not in backend)
        # Get the current file's directory (backend/utils/)
        current_dir = os.path.dirname(os.path.abspath(__file__))
        # Go up two levels to get to the root (backend/utils/ -> backend/ -> root/)
        root_dir = os.path.dirname(os.path.dirname(current_dir))
        reports_dir = os.path.join(root_dir, 'reports')
        
        # Create the reports folder if it doesn't exist
        os.makedirs(reports_dir, exist_ok=True)
        
        # Generate filename with timestamp
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = os.path.join(reports_dir, f'report_{period}_{timestamp}.pdf')
        
        # Create PDF document
        doc = SimpleDocTemplate(
            filename,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        story = []
        
        # TITLE
        title = f"Garment Defect Detection Report - {period.upper()}"
        story.append(Paragraph(title, self.styles['CustomTitle']))
        story.append(Spacer(1, 12))
        
        # META INFORMATION
        meta_info = f"""
        <para>
        <b>Generated By:</b> {user_name}<br/>
        <b>Date:</b> {datetime.now().strftime('%B %d, %Y at %H:%M')}<br/>
        <b>Period:</b> {period.capitalize()}
        </para>
        """
        story.append(Paragraph(meta_info, self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # SUMMARY STATISTICS
        story.append(Paragraph("Summary Statistics", self.styles['CustomHeading']))
        
        total = len(inspections)
        pass_count = sum(1 for i in inspections if i.result_summary == 'PASS')
        fail_count = total - pass_count
        pass_rate = (pass_count / total * 100) if total > 0 else 0
        
        stats_data = [
            ['Metric', 'Value'],
            ['Total Inspections', str(total)],
            ['Passed', str(pass_count)],
            ['Failed', str(fail_count)],
            ['Pass Rate', f"{pass_rate:.1f}%"],
            ['Total Defects Found', str(len(defects))],
        ]
        
        stats_table = Table(stats_data, colWidths=[200, 200])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f5f7fa')),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
        ]))
        story.append(stats_table)
        story.append(Spacer(1, 20))
        
        # DEFECT BREAKDOWN
        if defects:
            story.append(Paragraph("Defect Breakdown", self.styles['CustomHeading']))
            
            defect_counts = {}
            for defect in defects:
                defect_type = defect.defect_type
                defect_counts[defect_type] = defect_counts.get(defect_type, 0) + 1
            
            defect_data = [['Defect Type', 'Count']]
            for defect_type, count in defect_counts.items():
                defect_data.append([defect_type.replace('_', ' ').title(), str(count)])
            
            defect_table = Table(defect_data, colWidths=[250, 150])
            defect_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#c62828')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
            ]))
            story.append(defect_table)
            story.append(Spacer(1, 20))
            
            # DETAILED DEFECT LIST (Last 10)
            story.append(Paragraph("Recent Defects", self.styles['CustomHeading']))
            
            defect_detail_data = [['Date', 'Type', 'Description', 'Severity']]
            for defect in defects[-10:]:
                defect_detail_data.append([
                    defect.created_at.strftime('%Y-%m-%d %H:%M'),
                    defect.defect_type.replace('_', ' ').title(),
                    defect.description[:40] + ('...' if len(defect.description) > 40 else ''),
                    defect.severity
                ])
            
            detail_table = Table(defect_detail_data, colWidths=[100, 100, 160, 70])
            detail_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0d47a1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cccccc')),
            ]))
            story.append(detail_table)
        
        # FOOTER
        story.append(Spacer(1, 40))
        footer = f"""
        <para align="center" fontSize="10" textColor="gray">
        Report generated by Garment Defect Detection System<br/>
        {datetime.now().strftime('%Y')} - All Rights Reserved
        </para>
        """
        story.append(Paragraph(footer, self.styles['Normal']))
        
        # BUILD PDF
        doc.build(story)
        
        return filename